/**
 * Fixed 30-scenario substrate for Milestone H observation (Lumen live QA pack lineage).
 * Source types are applied at queue generation time (`scenario`).
 */
export type ScenarioTemplate = {
  id: string;
  language: "en" | "zh";
  conversationType: "reflective" | "mixed" | "factual";
  signalStrength: "low" | "medium" | "high";
  previewText: string;
  fullInput: string;
  tags?: string[];
};

export const H_OBSERVATION_SCENARIO_PACK: ScenarioTemplate[] = [
  {
    id: "SCEN-01",
    language: "en",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "I feel overwhelmed with everything I need to do lately.",
    fullInput: "I feel overwhelmed with everything I need to do lately.",
    tags: ["pressure", "mild_affect"],
  },
  {
    id: "SCEN-02",
    language: "en",
    conversationType: "reflective",
    signalStrength: "high",
    previewText: "I have to get this perfect or I’ll disappoint everyone.",
    fullInput:
      "I have to get this perfect or I’ll disappoint everyone. I keep rewriting the same paragraph.",
    tags: ["proving", "worth_pressure"],
  },
  {
    id: "SCEN-03",
    language: "en",
    conversationType: "mixed",
    signalStrength: "medium",
    previewText: "Part of me wants rest; another part says I’m lazy if I stop.",
    fullInput:
      "Part of me wants rest; another part says I’m lazy if I stop. I don’t know which voice to trust.",
    tags: ["inner_split", "worth_pressure"],
  },
  {
    id: "SCEN-04",
    language: "en",
    conversationType: "factual",
    signalStrength: "low",
    previewText: "Can you summarize this article for me?",
    fullInput: "Can you summarize this article for me?",
    tags: ["utilitarian"],
  },
  {
    id: "SCEN-05",
    language: "en",
    conversationType: "factual",
    signalStrength: "low",
    previewText: "I need help writing an email.",
    fullInput: "I need help writing an email to my manager about PTO.",
    tags: ["utilitarian"],
  },
  {
    id: "SCEN-06",
    language: "en",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "I don’t feel anything in particular.",
    fullInput: "I don’t feel anything in particular.",
    tags: ["minimal_affect", "low_signal"],
  },
  {
    id: "SCEN-07",
    language: "en",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "I guess it’s okay.",
    fullInput: "I guess it’s okay.",
    tags: ["minimal_affect"],
  },
  {
    id: "SCEN-08",
    language: "en",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "I feel slightly uneasy but can’t explain why.",
    fullInput: "I feel slightly uneasy but can’t explain why.",
    tags: ["mild_affect", "low_signal"],
  },
  {
    id: "SCEN-09",
    language: "en",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "I’m a bit tense today.",
    fullInput: "I’m a bit tense today.",
    tags: ["mild_affect"],
  },
  {
    id: "SCEN-10",
    language: "en",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "I’m worried I might fail.",
    fullInput: "I’m worried I might fail the interview next week.",
    tags: ["worth_pressure"],
  },
  {
    id: "SCEN-11",
    language: "en",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "I don’t trust myself sometimes.",
    fullInput: "I don’t trust myself sometimes when I make quick decisions.",
    tags: ["worth_pressure"],
  },
  {
    id: "SCEN-12",
    language: "en",
    conversationType: "mixed",
    signalStrength: "medium",
    previewText: "I want to be honest but I’m afraid of the reaction.",
    fullInput:
      "I want to be honest with my partner but I’m afraid of the reaction.",
    tags: ["pressure"],
  },
  {
    id: "SCEN-13",
    language: "en",
    conversationType: "reflective",
    signalStrength: "high",
    previewText: "I feel like I have to prove I deserve to be here.",
    fullInput: "I feel like I have to prove I deserve to be in this role every day.",
    tags: ["proving", "worth_pressure"],
  },
  {
    id: "SCEN-14",
    language: "en",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "I’m exhausted but I keep pushing.",
    fullInput: "I’m exhausted but I keep pushing because stopping feels dangerous.",
    tags: ["pressure", "exhaustion"],
  },
  {
    id: "SCEN-15",
    language: "en",
    conversationType: "mixed",
    signalStrength: "low",
    previewText: "Not sure if this is the right place to ask…",
    fullInput:
      "Not sure if this is the right place to ask… I need a template for a cover letter.",
    tags: ["utilitarian", "uncertain_task"],
  },
  {
    id: "SCEN-16",
    language: "zh",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "最近压力很大，不知道从哪里开始。",
    fullInput: "最近压力很大，不知道从哪里开始。",
    tags: ["pressure"],
  },
  {
    id: "SCEN-17",
    language: "zh",
    conversationType: "reflective",
    signalStrength: "high",
    previewText: "我必须做到完美，否则就证明自己不行。",
    fullInput: "我必须做到完美，否则就证明自己不行。",
    tags: ["proving", "worth_pressure"],
  },
  {
    id: "SCEN-18",
    language: "zh",
    conversationType: "mixed",
    signalStrength: "medium",
    previewText: "一部分想休息，一部分又责怪自己懒。",
    fullInput: "一部分想休息，一部分又责怪自己懒。",
    tags: ["inner_split"],
  },
  {
    id: "SCEN-19",
    language: "zh",
    conversationType: "factual",
    signalStrength: "low",
    previewText: "能帮我总结一下这篇文章的要点吗？",
    fullInput: "能帮我总结一下这篇文章的要点吗？",
    tags: ["utilitarian"],
  },
  {
    id: "SCEN-20",
    language: "zh",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "没什么特别的感觉。",
    fullInput: "没什么特别的感觉。",
    tags: ["minimal_affect", "low_signal"],
  },
  {
    id: "SCEN-21",
    language: "zh",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "还行吧。",
    fullInput: "还行吧。",
    tags: ["minimal_affect"],
  },
  {
    id: "SCEN-22",
    language: "zh",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "有点不安，但说不清。",
    fullInput: "有点不安，但说不清。",
    tags: ["mild_affect"],
  },
  {
    id: "SCEN-23",
    language: "en",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "I keep comparing myself to others online.",
    fullInput: "I keep comparing myself to others online even when I know it hurts.",
    tags: ["worth_pressure"],
  },
  {
    id: "SCEN-24",
    language: "en",
    conversationType: "factual",
    signalStrength: "low",
    previewText: "What’s the capital of Norway?",
    fullInput: "What’s the capital of Norway?",
    tags: ["factual_plain"],
  },
  {
    id: "SCEN-25",
    language: "en",
    conversationType: "reflective",
    signalStrength: "high",
    previewText: "There are two versions of me arguing in my head.",
    fullInput:
      "There are two versions of me arguing in my head about whether to quit.",
    tags: ["inner_split", "explicit_split"],
  },
  {
    id: "SCEN-26",
    language: "en",
    conversationType: "mixed",
    signalStrength: "medium",
    previewText: "How do I stop spiraling when I get one critical comment?",
    fullInput:
      "How do I stop spiraling when I get one critical comment at work?",
    tags: ["pressure", "help_shaped"],
  },
  {
    id: "SCEN-27",
    language: "en",
    conversationType: "reflective",
    signalStrength: "low",
    previewText: "I’ve been overthinking again.",
    fullInput: "I’ve been overthinking again. Same loops.",
    tags: ["mild_affect", "low_signal"],
  },
  {
    id: "SCEN-28",
    language: "en",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "I feel numb after the argument.",
    fullInput: "I feel numb after the argument. I don’t know what I feel.",
    tags: ["mixed_state"],
  },
  {
    id: "SCEN-29",
    language: "zh",
    conversationType: "reflective",
    signalStrength: "medium",
    previewText: "我怕让别人失望。",
    fullInput: "我怕让别人失望，所以一直答应超出负荷的事。",
    tags: ["worth_pressure"],
  },
  {
    id: "SCEN-30",
    language: "zh",
    conversationType: "mixed",
    signalStrength: "low",
    previewText: "我不确定该问谁，能帮我改一下这段话吗？",
    fullInput: "我不确定该问谁，能帮我改一下这段话吗？",
    tags: ["utilitarian", "uncertain_task"],
  },
];
